lexik_jwt_authentication:
    # TODO use .env variables
    private_key_path: '%kernel.project_dir%/config/jwt/private.pem'
    public_key_path: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'qwerty'
